name: 'game_isar_scheme'
description: 'A Library for make game More easy'
version: '0.0.0'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: {}
dev_dependencies: 
  lints: '^4.0.0'
  test: 'any'
repository: 'https://github.com/azkadev/game'
homepage: 'https://github.com/azkadev/game'
issue_tracker: 'https://github.com/azkadev/game/issues'
documentation: 'https://github.com/azkadev/game/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
