name: 'game'
description: 'A Library for make game More easy'
version: '0.0.0'
homepage: 'https://github.com/azkadev/game'
repository: 'https://github.com/azkadev/game'
issue_tracker: 'https://github.com/azkadev/game/issues'
documentation: 'https://github.com/azkadev/game/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
dependencies: {}
